name = "VambBenchmarks"
uuid = "63a9268e-b9e5-4a07-aba6-1f52d4878f75"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LazilyInitializedFields = "0e77f7df-68c5-4e49-93ce-4cd80f5598bf"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
AbstractTrees = "0.4.2"
JSON3 = "1.9"
LazilyInitializedFields = "1.2"
PrecompileTools = "1"
StructTypes = "1.9"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
